site_name: Modules

nav:
  - Quickstart: docs/quickstart.md
  - Speedster: '!include nebullvm/apps/accelerate/speedster/docs/en/mkdocs.yaml'
  - nos: '!include nos/docs/en/mkdocs.yaml'

plugins:
  - monorepo
  - search  

theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
